In [7]:
import yfinance as yf
import pandas as pd

In [ ]:
tickers = {
    "DXY": "DX-Y.NYB",
    "EUR/USD": "EURUSD=X",
    "USD/JPY": "USDJPY=X",
    "GBP/USD": "GBPUSD=X",
    "USD/CHF": "USDCHF=X",
    "AUD/USD": "AUDUSD=X",
    "USD/CAD": "USDCAD=X",
    "NZD/USD": "NZDUSD=X",
    "USD/NOK": "USDNOK=X",
    "USD/BRL": "USDBRL=X",
    "USD/CLP": "USDCLP=X",
    "USD/PEN": "USDPEN=X",
    "USD/ZAR": "USDZAR=X",
    "USD/RUB": "USDRUB=X",
    "USD/COP": "USDCOP=X",
    "USD/CNY": "USDCNY=X",
    "USD/CNH": "USDCNH=X",
    "USD/KRW": "USDKRW=X",
    "USD/INR": "USDINR=X",
    "USD/SGD": "USDSGD=X",

    "EUR/GBP": "EURGBP=X",
    "EUR/CHF": "EURCHF=X",
    "EUR/JPY": "EURJPY=X",
    "AUD/JPY": "AUDJPY=X",
    "NZD/JPY": "NZDJPY=X",
    "CAD/JPY": "CADJPY=X",
    "CHF/JPY": "CHFJPY=X",
    "AUD/CAD": "AUDCAD=X",
    "AUD/NZD": "AUDNZD=X",
    "CAD/CHF": "CADCHF=X",
}

In [9]:
end_date = pd.Timestamp.today().normalize()

df = yf.download(
    tickers=symbols,
    start="1990-01-01",
    end=end_date,
    interval="1d",
    auto_adjust=False,
    group_by="ticker",
    threads=True
)

[*********************100%***********************]  30 of 30 completed

In [10]:
df.to_parquet("fx_data.parquet")

In [12]:
df.head()

Ticker     USDKRW=X                                   DX-Y.NYB             \
Price          Open High Low Close Adj Close Volume       Open       High
Date
1990-01-01      NaN  NaN NaN   NaN       NaN    NaN  93.190002  93.309998
1990-01-02      NaN  NaN NaN   NaN       NaN    NaN  93.129997  94.309998
1990-01-03      NaN  NaN NaN   NaN       NaN    NaN  94.150002  94.519997
1990-01-04      NaN  NaN NaN   NaN       NaN    NaN  93.720001  93.879997
1990-01-05      NaN  NaN NaN   NaN       NaN    NaN  93.339996  93.419998

Ticker                            ... NZDJPY=X                         \
Price             Low      Close  ...      Low Close Adj Close Volume
Date                              ...
1990-01-01  93.080002  93.209999  ...      NaN   NaN       NaN    NaN
1990-01-02  93.080002  94.290001  ...      NaN   NaN       NaN    NaN
1990-01-03  94.080002  94.419998  ...      NaN   NaN       NaN    NaN
1990-01-04  92.389999  92.519997  ...      NaN   NaN       NaN    NaN
1990-01-05  92.550003  92.849998  ...      NaN   NaN       NaN    NaN

Ticker     NZDUSD=X
Price          Open High Low Close Adj Close Volume
Date
1990-01-01      NaN  NaN NaN   NaN       NaN    NaN
1990-01-02      NaN  NaN NaN   NaN       NaN    NaN
1990-01-03      NaN  NaN NaN   NaN       NaN    NaN
1990-01-04      NaN  NaN NaN   NaN       NaN    NaN
1990-01-05      NaN  NaN NaN   NaN       NaN    NaN

[5 rows x 180 columns]

In [13]:
df_close = df.xs("Close", level=1, axis=1)

df_close.to_parquet("fx_close.parquet", engine="pyarrow")

In [15]:
df_close.tail()

Ticker,USDKRW=X,DX-Y.NYB,USDCOP=X,AUDJPY=X,USDNOK=X,AUDNZD=X,AUDCAD=X,GBPUSD=X,USDCLP=X,USDBRL=X,...,USDRUB=X,USDSGD=X,EURJPY=X,CHFJPY=X,USDCAD=X,EURUSD=X,USDINR=X,CADCHF=X,NZDJPY=X,NZDUSD=X
Date,,,,,,,,,,,,,,,,,,,,,
2026-04-13,1482.180054,98.370003,3643.709961,112.081001,9.53555,1.20942,0.97364,1.339441,894.440002,5.00500,...,76.548508,1.27767,186.423996,201.435455,1.38727,1.167515,94.508797,0.57128,92.657997,0.580430
2026-04-14,1476.839966,98.120003,3598.229980,113.023003,9.43715,1.20903,0.97852,1.351534,894.890015,4.99440,...,76.165710,1.27150,187.341995,203.257996,1.37850,1.176886,94.946800,0.56803,93.466003,0.587199
2026-04-15,1469.420044,98.059998,3595.010010,113.200996,9.43261,1.20765,0.98124,1.357534,886.229980,4.98480,...,75.371872,1.27079,187.354996,203.332169,1.37661,1.179941,93.165398,0.56719,93.723000,0.590350
2026-04-16,1474.060059,98.220001,3615.149902,113.950996,9.37955,1.21375,0.98509,1.357370,884.950012,4.99240,...,75.492355,1.27065,187.503006,203.245209,1.37313,1.180916,93.386803,0.56892,93.867996,0.591219
2026-04-17,1465.680054,98.099998,3613.030029,113.703003,9.35376,1.21629,0.98079,1.351587,886.119995,4.98709,...,76.370575,1.27312,186.604996,202.957001,1.37004,1.176747,92.574997,0.57160,93.327003,0.588609